#!/usr/bin/python
#
# A Pythagorean triplet is a set of three natural
# numbers, a  b  c, for which, a^2 + b^2 = c^2
# For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
#
# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
# Find the product abc.

import math,sys

# must be whole number square roots
# greatest number in set is < sqrt(1000)
# a + b + a^2 + b^2 = 1000

a = 0
b = 0
c = 0

def is_whole(x):
  if x % 1 == 0:
    return True
  return False

def square(x):
  return x * x

def equation(x,y):
  return x + y + math.sqrt(square(x) + square(y))

for element1 in range(1,1000):
  for element2 in range(1,1000):
    if is_whole(math.sqrt(square(element1) + square(element2))):
      if equation(element1,element2) == 1000:
        a = element1
        b = element2
        c = 1000 - (a + b)
        print str(a),str(b),str(c)
        print str(a * b * c)
        sys.exit(0)

