#!/usr/bin/python
# Dan Neff - (dan@neff.cc)
#
# 
# How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2  <= b <= 100?
#

import math,sys

distinct = []

def power_up(a,b):
  return a**b

for a in range(2,100 + 1):
  for b in range(2,100 +1):
    if power_up(a,b) not in distinct:
      distinct.append(power_up(a,b))

print len(distinct)
