#!/usr/bin/python
# Dan Neff - (dan@neff.cc)
#
# Pentagonal numbers are generated by the formula, Pn=n(3n1)/2.
# The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their 
# difference, 70  22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their
# sum and difference is pentagonal and D = |Pk  Pj| is minimised; 
# what is the value of D?
#
import math,sys

def pentagonal(x):
  return x * (3 * x - 1) / 2

def is_pentagonal(x):
  if math.sqrt(24 * x + 1) == int(math.sqrt(24 * x +1)):
    if math.sqrt(24 * x +1) % 6 == 5:
      return True
  return False

j = 0

solution = 0

while solution == 0:
  for k in range(1,j+1):
    if j == k:
      continue
    if is_pentagonal(pentagonal(j) - pentagonal(k)) and is_pentagonal(pentagonal(j) + pentagonal(k)):
        solution = (pentagonal(j) - pentagonal(k))
  j += 1

print solution
