#!/usr/bin/python
# Dan Neff - (dan@neff.cc)
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal  Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n-1)     1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
#
import math,sys

def hexagonal(x):
  return x * (2 * x - 1)

def is_pentagonal(x):
  if math.sqrt(24 * x + 1) == int(math.sqrt(24 * x + 1)):
    if math.sqrt(24 * x + 1) % 6 == 5:
      return True
  return False

def is_triangle(x):
  if math.sqrt(8 * x + 1) == int(math.sqrt(8 * x + 1)):
    if math.sqrt(8 * x + 1) % 2 == 1:
      return True
  return False

def is_hexagonal(x):
  if math.sqrt(8 * x + 1) == int(math.sqrt(8 * x + 1)):
    if math.sqrt(8 * x + 1) % 4 == 3:
      return True
  return False

solution = 0
seeking = True
x = 1

while seeking:
  x += 1
  solution = hexagonal(x)
  if is_hexagonal(solution) and is_pentagonal(solution) and is_triangle(solution):
    if solution > 40755:
      seeking = False

print solution
